### ISSUE TITLE
Feature Request: Companion v2 Preset icons

### ISSUE THREAD

**Issue by bryce-seifert** [thedist/companion-module-utils#2]
Add Companion v2 preset icons to allow devs to continue using them across modules

List of icons:
https://github.com/bitfocus/companion/commit/0a9550e907cafad69e50dd1ef1cd6886c90918e1

**Comment by thedist** [comment]
Sorry for the delay in getting these added, as I've been ill over the Christmas period so have only now been able to get these added in the version I just published, 0.4.0.

https://github.com/thedist/companion-module-utils/blob/main/docs/graphics.md#icon has the docs for how to generate the icons, and as Presets don't support an imagebuffer like a feedback does, you'll need to use https://github.com/thedist/companion-module-utils/blob/main/docs/graphics.md#topng64 to convert the buffer into a png64 for use in Presets.
